CloudPrinter/Models/UserModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CloudPrinter.Models
{
    public class UserModels
    {
        [Required]
        //[StringLength(64)]
        [Key]
        [DataType(DataType.EmailAddress)]
        //[Index(IsUnique =true)]
        [Display(Name ="账号")]
        public virtual string userAccount { get; set; }

        [StringLength(64)]
        [Display(Name ="用户名")]
        public virtual string Name { get; set; }

        [Required]
        [StringLength(13)]
        [DataType(DataType.Password)]
        [Display(Name ="密码")]
        public virtual string password { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        [Display(Name = "注册时间")]
        public virtual DateTime registerDate { get; set; }

    }
}

CloudPrinter/Controllers/PrinterModelsController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using CloudPrinter.Models;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Web;

namespace CloudPrinter.Controllers
{
    public class PrinterModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        int length = 20;

        // GET: PrinterModels/5
        public ActionResult Index(string userAccount)
        {
            Response.CacheControl = "no-cache";
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            ViewBag.superAccount = superAdmin.AdminInfo.ADMINACCOUNT;
            ViewBag.userAccount = userAccount;
            HttpCookie cookie = new HttpCookie("ToCount");
            cookie["count"] = "0";
            if (Request.Cookies.Get("ToCount") != null)
            {
                Response.Cookies.Set(cookie);
            }
            else
            {
                Response.Cookies.Add(cookie);
            }
            Response.Cookies["ToCount"].Expires = DateTime.Now.AddHours(2);
            cookie.Expires = DateTime.Now.AddHours(2);
            Response.Cookies.Add(cookie);
            List<PrinterModels> li = new List<PrinterModels>();
            li = db.PrinterModels.OrderBy(c => c.printerNumber).Skip(co * length).Take(length).ToList();
            return View(li);
        }

        // GET: PrinterModels/Details/5
        public ActionResult Details(string printerNumber)
        {

            if (printerNumber == null || printerNumber == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Device");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            PrinterModels printerModels = db.PrinterModels.Find(printerNumber);
            if (printerModels == null)
            {
                return HttpNotFound();
            }
            return View(printerModels);
        }

        // GET: PrinterModels/Create/5
        public ActionResult Create(string userAccount)
        {
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            ViewBag.userAccount = userAccount;
            return View();
        }

        // POST: PrinterModels/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userAccount,printerNumber,printerName")] PrinterModels printerModels, string maxPrinter)
        {
            if (maxPrinter != printerModels.printerNumber)
            {
                long max = Convert.ToInt64(maxPrinter, 16);
                long min = Convert.ToInt64(printerModels.printerNumber, 16);
                var umodel = db.UserModels.Find(printerModels.userAccount);
                for (long i = 0; i < max - min; i++)
                {
                    long number = min + i;
                    PrinterModels printer = new PrinterModels()
                    {
                        printerNumber = string.Format("{0:X16}", number),
                        printerName = printerModels.printerName,
                        cState = "ready",
                        stateMessage = "就绪",
                        userName = umodel.Name,
                        userAccount = printerModels.userAccount,
                        registerTime = DateTime.Now,
                        mState = false
                    };
                    var print = db.PrinterModels.Find(printer.printerNumber);
                    if (printer == null)
                    {
                        db.PrinterModels.Add(printer);
                    }
                }
                db.SaveChanges();
                return RedirectToAction("Index", new { userAccount = printerModels.userAccount });
            }
            else
            {
                ModelState.Remove("cState");
                printerModels.cState = "ready";
                printerModels.stateMessage = "就绪";
                var umodel = db.UserModels.Find(printerModels.userAccount);
                printerModels.userName = umodel.Name;
                printerModels.registerTime = DateTime.Now;
                if (ModelState.IsValid)
                {
                    db.PrinterModels.Add(printerModels);
                    db.SaveChanges();
                    return RedirectToAction("Index", new { userAccount = printerModels.userAccount });
                }
            }

            return View(printerModels);
        }

        // GET: PrinterModels/Edit/5
        public ActionResult Edit(string printerNumber)
        {
            if (printerNumber == null || printerNumber == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Device");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            ViewBag.superAccount = superAdmin.AdminInfo.ADMINACCOUNT;
            PrinterModels printerModels = db.PrinterModels.Find(printerNumber);
            if (printerModels == null)
            {
                return HttpNotFound();
            }
            return View(printerModels);
        }

        // POST: PrinterModels/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "printerNumber,printerName,cState")] PrinterModels printerModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(printerModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { userAccount = printerModels.userAccount });
            }
            return View(printerModels);
        }

        // GET: PrinterModels/Delete/5
        public ActionResult Delete(string printerNumber)
        {
            if (printerNumber == null || printerNumber == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Device");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            PrinterModels printerModels = db.PrinterModels.Find(printerNumber);
            if (printerModels == null)
            {
                return HttpNotFound();
            }
            return View(printerModels);
        }

        // POST: PrinterModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string printerNumber)
        {
            PrinterModels printerModels = db.PrinterModels.Find(printerNumber);
            var userAccount = printerModels.userAccount;
            db.PrinterModels.Remove(printerModels);
            db.SaveChanges();
            return RedirectToAction("Index", new { userAccount = userAccount });
        }
        int co = 0;
        // GET : PrinterModels/PerUserList/5
        [HttpPost]
        public ActionResult PerUserList(string userAccount)
        {
            Response.CacheControl = "no-cache";
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            ViewBag.superAccount = superAdmin.AdminInfo.ADMINACCOUNT;
            ViewBag.userAccount = userAccount;

            List<PrinterModels> li = new List<PrinterModels>();
            co = Int32.Parse(Request.Cookies.Get("ToCount").Values["count"]);
            try
            {
                li = db.PrinterModels.OrderBy(c => c.printerNumber).Skip(co * length).Take(length).ToList();
            }
            catch (Exception ex)
            {
                string s = string.Format("{0}", ex);
            }
            return PartialView("PerUserList", li);
        }
        [HttpPost]
        public ActionResult upToList(string userAccount)
        {
            HttpCookie cookie = Request.Cookies["ToCount"];
            if (cookie != null)
            {

CloudPrinter/Controllers/UserModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CloudPrinter.Models;
using System.Collections.Concurrent;

namespace CloudPrinter.Controllers
{
    public class UserModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: UserModels
        public ActionResult Index()
        {
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            return View(db.UserModels.ToList());
        }

        // GET: UserModels/Details/5
        public ActionResult Details(string userAccount)
        {
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            UserModels userModels = db.UserModels.Find(userAccount);
            if (userModels == null)
            {
                return HttpNotFound();
            }
            return View(userModels);
        }

        // GET: UserModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserModels/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "userAccount,Name,password")] UserModels userModels, string referrer,string code)
        {
            if (ModelState.IsValid)
            {
                if (Session["vcode"].Equals(code.ToLower()))
                {
                    userModels.registerDate = DateTime.Now;
                    db.UserModels.Add(userModels);
                    db.SaveChanges();
                    return Redirect(referrer);
                }else
                {
                    ModelState.AddModelError(string.Empty, "验证码错误");
                }
            }
            ModelState.AddModelError("", "创建账户失败！");
            return View();
        }

        // GET: UserModels/Edit/5
        public ActionResult Edit(string userAccount)
        {
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            UserModels userModels = db.UserModels.Find(userAccount);
            if (userModels == null)
            {
                return HttpNotFound();
            }
            return View(userModels);
        }

        // POST: UserModels/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "userAccount,Name,password")] UserModels userModels)
        {
            if (ModelState.IsValid)
            {
                var um = db.UserModels.Find(userModels.userAccount);
                if (um != null)
                {
                    um.Name = userModels.Name;
                    um.password = userModels.password;
                    db.Entry(userModels).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }else
                {
                    return HttpNotFound();
                }
            }
            return View(userModels);
        }

        // GET: UserModels/Delete/5
        public ActionResult Delete(string userAccount)
        {
            if (userAccount == null || userAccount == "")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "no find Account");
            }
            var result = Request.Cookies.Get("LoginAccount").Value;
            if (result == "" || result == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Account is Expire");
            }
            ViewBag.loginAccount = result;
            UserModels userModels = db.UserModels.Find(userAccount);
            if (userModels == null)
            {
                return HttpNotFound();
            }
            return View(userModels);
        }

        // POST: UserModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string userAccount)
        {
            UserModels userModels = db.UserModels.Find(userAccount);
            db.UserModels.Remove(userModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CloudPrinter/Views/UserModels/Create.cshtml
@model CloudPrinter.Models.UserModels

@{
    ViewBag.Title = "创建用户";
}

<h2>创建账户</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.Hidden("referrer", Request.UrlReferrer.ToString())
    <div class="form-horizontal">
        <h4>账户信息</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.userAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userAccount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-10" style="width:100%;padding-left:18%">
                <table style="width:40%">
                    <tr>
                        <td style="width:10%">
                            <input type="text" name="code" style="width:100%" />
                        </td>
                        <td style="width:10%">
                            <img id="vcodeimg" src="/UserLogin/VCode" style="width:100%;height:100%" />
                        </td>
                        <td style="width:20%">
                            <input type="submit" style="cursor: pointer; text-decoration: underline;width:50%;border:hidden;padding-left:15px;background-color:azure" id="nextImg" value="更换">
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="创建" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@*<div>
        <a href="#" onclick="javascript:history.back();">返回前一页</a>
    </div>*@

CloudPrinter/Views/UserModels/Delete.cshtml
@model CloudPrinter.Models.UserModels

@{
    ViewBag.Title = "删除账户";
}

<h2>删除</h2>

<h3>你确定想要删除?</h3>
<div>
    <h4>账户信息</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.userAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.registerDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.registerDate)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
        </div>
    }
</div>

CloudPrinter/Views/UserModels/Details.cshtml
@model CloudPrinter.Models.UserModels

@{
    ViewBag.Title = "账户信息列表";
}

<h2>信息表</h2>

<div>
    <h4>账户信息</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.userAccount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userAccount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.registerDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.registerDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { userAccount = Model.userAccount }) |
    @Html.ActionLink("查看该用户的设备信息", "index", "PrinterModels", new { userAccount = Model.userAccount }, null)
</p>

CloudPrinter/Views/UserModels/Edit.cshtml
@model CloudPrinter.Models.UserModels

@{
    ViewBag.Title = "编辑账户信息";
}

<h2>编辑</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>账户信息</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.userAccount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userAccount, new { htmlAttributes = new { @class = "form-control",@readonly=true } })
                @Html.ValidationMessageFor(model => model.userAccount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

CloudPrinter/Views/UserModels/Index.cshtml
@model IEnumerable<CloudPrinter.Models.UserModels>

@{
    ViewBag.Title = "主界面";
}

<h2>账户主页面</h2>

<p>
    @Html.ActionLink("创建新账户", "Create") |
    @Html.ActionLink("注册新打印机", "Create","PrinterModels",new { userAccount=ViewBag.loginAccount},"")
</p>
<div>
    <input class="auto" name="userAccoount" data-autocomplete-id=@Url.Action("Index")/>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.userAccount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.registerDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.userAccount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.registerDate)
        </td>
        <td>
            @Html.ActionLink("编辑", "Edit", new { userAccount=item.userAccount }) |
            @Html.ActionLink("信息", "Details", new { userAccount = item.userAccount }) |
            @Html.ActionLink("删除", "Delete", new { userAccount = item.userAccount })
        </td>
    </tr>
}

</table>
@*<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script>
    var option = {
        source: $(".auto").attr("data-autocomplete-id")
    };
    $(".auto").autocomplete(option);
</script>*@